### ISSUE TITLE
IndentationError

### ISSUE THREAD

**Issue by SkepticMystic** [cristianvasquez/obsidian-snippets-plugin#3]
I am having an issue running snippets with indentations. I changed the config to call `py` instead of `python3`, which allows _some_ snippets to run. But in the following example, I get this error, even when using different numbers of spaces or tabs.

```python
for i in [0,1,2]:
    print(i)
```

```output
Error: Command failed: py -c "for i in [0,1,2]:
    print(i)"
  File "<string>", line 1
    for i in [0,1,2]:
                     ^
IndentationError: expected an indented block
```

But when I run the snippet as follows, it works.

```python
for i in [1,2,3]: print(i)
```
```output
1
2
3
```

Is this unavoidable at the moment, or am I doing something wrong?

**Comment by steve-bate** [comment]
Are you running the snippet on Windows 10? If so, I had the same issue. The problem is that node `child_process.exec` uses `cmd.exe` as the default exec shell on Windows. Apparently, `cmd.exe` doesn't handle the line endings well. Node uses `process.env.ComSpec` to configure the shell. I changed this (in devtools) to the PowerShell path on my system and the multiline snippets worked fine. 

This plugin should probably add a setting for process.env.ComSpec when running on Windows.

**Comment by cristianvasquez** [comment]
Hello all!, thank you for the issue and commit. 

I've added the 'options' property to the latest version, where you can specify the shell to use.
